baseURL = 'https://mombe090.github.io/blog/'
languageCode = 'fr-fr'
title = 'Un Dev perdu dans le monde des Ops'
theme = "hugo-blog-awesome"


[params]
    goToTop = true
    [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com"

    [[params.socialIcons]]
    name = "Rss"
    url = "index.xml"